title: MIRS Perfumes
description: MIRS je EDP parfem za žene koji spaja sofisticiranost i neukrotivu prirodu.
baseurl: "/mirs"  # Mora početi s kosom crtom, naziv repozitorija
url: "https://banovotz.github.io"
permalink: /blog/:title/
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
